# See https://squidfunk.github.io/mkdocs-material/
# https://www.mkdocs.org/user-guide/deploying-your-docs/#organization-and-user-pages

site_name: biocommons

theme:
  name: material

  features:
    - navigation.indexes
    - navigation.instant
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - toc.follow
    - toc.integrate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Ubuntu
    code: Roboto Mono
  logo: images/logo.svg
  favicon: images/logo.png
# nav:
#   - About:
#       - Executive Summary: executive-summary.md
#       - Mission: mission.md
#       - Governance: governance.md
#   - Project Teams: project-teams.md
#   - Meetings:
#       - Somewhere Over the Rainbow: meeting.md
